#https://github.com/MarcIMP08/Luegendetektor/blob/master/main.py

from csv import excel
import panda as pd
excel-datei = pd.read_excel("Fragen.xlsx")

def excel():
  print(excel-datei)
  print(excel-datei.iloc[1, 2])

print("_______________________________________________________________________________ ")

import csv
with open('csv-test.csv') as f:
    reader = csv.reader(f)
    data = list(reader)
print(data)

import numpy as np
print("Standartabweichung ist: ", np.std(y))

print("_______________________________________________________________________________ ")
print("Frage 1: \n Wo warst du um die Uhrzeit? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 2: \n Hast du ein Alibi? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 3: \n Bist du das auf den Kameraaufnahmen? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 4: \n Wann bist du an dem Tag aufgestanden? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 5: \n Wer war der Täter? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 6: \n Was haben sie zum Frühstück gegessen? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 7: \n Hast du eine Freundin? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 8: \n Wie lange schläfst du pro Nacht? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 9: \n Warum hast du das gemacht? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 10: \n Waren sie an dem Tag draußen?  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 11: \n Waren sie schon einmal in München? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 12: \n Gibt es Zeugen dass du nicht bei dem Fall dabei warst? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 13: \n Wo bist du geboren? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 14: \n  Welche Staatsangehörigkeit bist du?  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 15: \n Gehst du oft in Urlaub? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 16: \n Hast du einen job? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 17: \n Hast du eine Ausbildung? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 18: \n Wie war das Wetter an dem Tag? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 19: \n Welche welche Klassen hast du einen Führerschein? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 20: \n Bist du traurig dass deine Oma gestorben ist? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 21: \n Wo waren sie um 8.00 Uhr? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 22: \n Was hattest du an dem Tag an? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 23: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 24: \n Lieber lebenslang im Gefängnis oder tot? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 25: \n Warum hast du das gemacht? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 26: \n  Wann war deine letzte Mahlzeit? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 27: \n Wie war das Wetter um 8 Uhr? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 28: \n Warst du um 19:50 Uhr zuhause? Wenn ja mit deiner Freundin? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 29: \n Woher kennst du deine Freundin? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 30: \n Wie ging es dir um 17:45 Uhr? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 31: \n Hast du Punkte in Flensburg, wenn ja wie viele? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 32: \n Hast du schonmal Urlaub in Österreich gemacht? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 33: \n Welche Farbe hatte deine Hose? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 34: \n Leben deine Großeltern noch? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 35: \n Hast du ein Alibi? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 36: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 37: \n Besitzt du ein Waffenschein? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 38: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 39: \n Wissen sie wie man aus der Münchner Innenstadt kommt? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 40: \n Welche Farbe hatte dein Oberteil an deisem Tag? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 41: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 42: \n Was haben sie um 18:00 Uhr gemacht? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 43: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 44: \n Wie war ihr Tagesablauf? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 45: \n Warst du schonmal in Österreich? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 46: \n Haben sie einen Hund? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 47: \n Kennst du die Freundin deiner Freundin, die sich euch angeschlossen hast? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 48: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 49: \n Was hast du an dem Tag gemacht? Gibt es dafür Zeugen? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 50: \n Für welche Klassen hast du einen Führerschein? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 51: \n Wie war das Wetter um 10:25 Uhr? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 52: \n Wer war der Täter? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 53: \n Welche Art von Hose hattest du an? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 54: \n Warst du schon einmal bei der Polizei? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 55: \n Wo warst du um 19:50 Uhr? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 56: \n Kennst du dich in München aus? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 57: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 58: \n Hast du Geschwister? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 59: \n Hast du ein Smartphone? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 60: \n Welche Farbe hatte deine Hose? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 61: \n Besitzt du Waffen? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 62: \n Warst du an dem Tag müde? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 63: \n Hast du um 15:45 Uhr mit jemanedem Kontakt gehabt? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 64: \n Warst du noch nie in München? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 65: \n Sind sie in Bayern geboren? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 66: \n Wie war das Wetter um 8 Uhr? \n Antwort: ")
print("_______________________________________________________________________________ ")
print("Frage 67: \n Welche Staatsangehörigkeit bist du? \n Antwort: ")
print("_______________________________________________________________________________ ")
print("Frage 68: \n Warst du schonmal in Österreich? \n Antwort: ")
print("_______________________________________________________________________________ ")
print("Frage 69: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 70: \n Hast du ein Alibi? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 71: \n Hast du eine Waffenlizenz? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 72: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 73: \n Hast du ein Studium? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 74: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 75: \n Was haben sie um 18:00 Uhr gemacht? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 76: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 77: \n Was haben sie heute gemacht? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 78: \n Welche welche Klassen hast du einen Führerschein? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 79: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 80: \n Welche Art von Hose hattest du an? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 81: \n Hatst du dich mal sozial engagiert? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 82: \n Wie heißt ihr Hund? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 83: \n Wie war das Wetter um 10:25 Uhr? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 84: \n Sprechen sie mit Akzent? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 85: \n Hast du dich um 19:50 Uhr mit jemandem getroffen? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 86: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 87: \n Wo warst an dem Tag? Gibt es irgendwelche Zeugen dafür? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 88: \n Wie ging es dir um 17:45 Uhr? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 89: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 90: \n Würdest du lieber eine junge oder ältere Person töten? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 91: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 92: \n Leben deine Großeltern noch? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 93: \n Kennst du die Freundin deiner Freundin, die sich euch angeschlossen hast? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 94: \n Gibt es Zeugen dass du bei dem Fall dabei warst? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 95: \n Welche Farbe hatte dein Oberteil an deisem Tag? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 96: \n Bist du vorbestraft? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 97: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 98: \n Was genau hast du am 18. August um 15:45 Uhr gemacht? \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 99: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
print("Frage 100: \n  \n Antwort:")
print("_______________________________________________________________________________ ")
